### PR TITLE
Add meta tags for social sharing

### PR DESCRIPTION
**Pull request by lavingiasa**
image

### CODE REVIEW

**Comment by lavingiasa** [comment]
Tested on https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-16--enchanting-fenglisu-1cc190.netlify.app%2F

**Comment by lavingiasa** [comment]
Updated illustration to use Liz's

**Comment by akgerber** [comment]
test
https://deploy-preview-16--enchanting-fenglisu-1cc190.netlify.app/

**Review by akgerber — APPROVED** [review]
lgtm
image

**Pull request merged**
